// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sabndgaxyzczmisusouv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhYm5kZ2F4eXpjem1pc3Vzb3V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyOTgxMTAsImV4cCI6MjA2Mjg3NDExMH0.IeNqbE2l6qcANZnKg-irxDXBagJvkln1TKMYUW9WhxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);